-- One row per file that arrived at the upload endpoint, minted before the
-- application it belongs to exists.
--
-- The application row is created at submit, and the resume is uploaded before
-- that — somebody picks a file part-way down a long form and the bytes want to
-- be moving while they finish the rest of it. So the upload cannot write
-- resume_key directly, and something has to carry the key across the gap.
--
-- That something is deliberately not the browser. If the page handed the key
-- back at submit, the key would be a caller-supplied string that names a blob:
-- the same shape of mistake as trusting a field list that arrives with the
-- answers, and here it would let somebody attach a blob that is not theirs, or
-- write a path with a `..` in it into a column the review tool reads. The page
-- gets an opaque id of a row we wrote instead, and the key never leaves this
-- side.

CREATE TABLE applications.resume_uploads (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Which form the upload was for. Checked again at claim time, so a ticket
    -- minted against one form cannot be spent on another.
    form_id     uuid        NOT NULL
                            REFERENCES applications.forms (id) ON DELETE CASCADE,

    -- Where the bytes are. Generated by the API and never derived from what
    -- the file was called.
    storage_key text        NOT NULL UNIQUE,

    -- What it was called on the applicant's machine, kept only so a reviewer
    -- sees a name they recognise. It is attacker-controlled text and nothing
    -- reads it as a path.
    filename    text        NOT NULL,

    -- Measured while the bytes were read, not taken from the request. The
    -- number a caller sends is a claim about a file we are holding anyway.
    size        int         NOT NULL,

    created_at  timestamptz NOT NULL DEFAULT now(),

    -- Set in the same transaction as the INSERT that puts the key on an
    -- application. Non-null is what makes a ticket spent: one upload can back
    -- exactly one application, so a replayed submit cannot re-point somebody
    -- else's row at these bytes.
    claimed_at  timestamptz
);

-- Finds the uploads nobody ever submitted, which is the ordinary outcome of
-- closing the tab half-way through. There is no sweeper yet; this index is
-- what one will read, and until it exists the orphans are a storage bill
-- rather than a correctness problem.
CREATE INDEX resume_uploads_unclaimed_idx
    ON applications.resume_uploads (created_at) WHERE claimed_at IS NULL;
