namespace MorganHacks.Applications.Services;

/// <summary>A way to read one resume, for a few minutes.</summary>
public sealed record SignedResume(Uri Url, DateTimeOffset ExpiresAt);

/// <summary>
/// Thrown when a resume is asked for and the store cannot reach it.
/// </summary>
/// <remarks>
/// Separated from "there is no resume", which is an ordinary answer. This one
/// means the row says there are bytes and the store disagrees, which is
/// something to fix rather than something to tell a reviewer to try again.
/// </remarks>
public sealed class ResumeMissingException(string message) : InvalidOperationException(message);

/// <summary>
/// Where resumes live.
/// </summary>
/// <remarks>
/// Deliberately says nothing about which object store is underneath. That is
/// the portability the plan asks for, and it is bought here rather than by
/// picking a vendor: what is written to the database is a key that only this
/// interface knows how to resolve, so moving providers is a new implementation
/// and a copy of the objects, with no column to rewrite and nothing already
/// emailed that stops working.
/// <para>
/// A URL in <c>resume_key</c> would be the opposite of that. URLs expire, get
/// pasted into messages, and turn into a way to read somebody's CV without
/// signing in — which is why the column comment says a key and never a URL.
/// </para>
/// </remarks>
public interface IResumeStore
{
    /// <summary>
    /// How long a link lives.
    /// </summary>
    /// <remarks>
    /// Long enough to open the file, short enough that a URL copied out of a
    /// browser's address bar and pasted into a group chat is already dead. It
    /// is stated once, here, so no implementation can quietly sign for longer.
    /// </remarks>
    static readonly TimeSpan LinkLifetime = TimeSpan.FromMinutes(5);

    /// <summary>
    /// Whether this store is configured well enough to be used.
    /// </summary>
    /// <remarks>
    /// False rather than a crash at startup, matching how Google sign-in is
    /// registered: a missing storage account leaves the upload endpoint
    /// answering 503 and everything else working, instead of taking the whole
    /// API down. Somebody running this locally for the first time should get a
    /// form they can submit without a resume, not a service that will not
    /// boot.
    /// </remarks>
    bool Available { get; }

    /// <summary>
    /// Writes one resume and answers with the key it was written under.
    /// </summary>
    /// <remarks>
    /// The key is generated by the store, never passed in. A caller that names
    /// its own key is a caller that can overwrite somebody else's, and the only
    /// name available at this point came from the uploaded file.
    /// </remarks>
    Task<string> StoreAsync(
        Guid eventId, ReadOnlyMemory<byte> content, CancellationToken ct = default);

    /// <summary>
    /// A link a reviewer's browser can follow, for <see cref="LinkLifetime"/>.
    /// </summary>
    /// <remarks>
    /// The link carries the type and the disposition with it, so the file
    /// arrives as a PDF called <paramref name="downloadName"/> however it was
    /// stored. That pairing is the point: these are files strangers uploaded,
    /// and the one thing that must not happen is a browser deciding for itself
    /// what one of them is.
    /// </remarks>
    Task<SignedResume> LinkToAsync(
        string storageKey, string downloadName, CancellationToken ct = default);
}
